# Maintenance Announcer 5 Config File
# Need help with Maintenance Announcer? Get help here: https://haydenwatson.co/maintenance-announcer
adminOnlyMaintenance: false
Maintenance: false

# Settings
# Allow the Maintenance Announcer plugin to be reloaded. (default: true)
Allow reloads to Maintenance Announcer: true


# ----Message Customization------------------------------------------------------------------
# Here's where you can customize every message.
Maintenance has started: '&f Maintenance to the server has started. Please excuse any lag.'
Maintenance has ended: '&f Maintenance to the server has ended. Thanks for your patience.'
Invalid argument message: '&a Invalid Argument! Args: start, begin, stop, end, admin start, admin begin, admin stop, admin end, reload.'
Maintenance ongoing message: '&f The server is currently undergoing maintenance. Please excuse any lag.'
Maintenance not ongoing message: '&f The server is not currently undergoing maintenance.'
Prefix: '&c[Maintenance Announcer]'
Admin only prefix: '&c[Maintenance Announcer (ADMIN ONLY)]'
Sent to all admins message: '&a Sent to ALL admins!'
Two arguments are needed message: '&a2 arguments are needed!'

# Made with love in Tennessee.
